name: CD

on:
  release:
    types:
      - created # Trigger this workflow only when a new release is created

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  package-linux:
    name: Package Linux App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Setup Fyne
        uses: ./.github/actions/fyne-linux-setup

      - name: Install Fyne tool
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Read metadata
        run: |
          APP_NAME=$(grep '^Name' FyneApp.toml | sed 's/.*= "\(.*\)"/\1/')
          APP_VERSION=$(grep '^Version' FyneApp.toml | sed 's/.*= "\(.*\)"/\1/')
          ARCH=$(uname -m)

          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "ARCH=$ARCH" >> $GITHUB_ENV

          echo "Packaging $APP_NAME version $APP_VERSION for linux/$ARCH"

      - name: Package application for Linux
        run: fyne package --release

      - name: Rename Linux package
        run: |
          ORIGINAL="${APP_NAME}.tar.xz"
          TARGET="${APP_NAME}-${APP_VERSION}-linux-${ARCH}.tar.xz"

          mv "$ORIGINAL" "$TARGET"

          echo "ARCHIVE=$TARGET" >> $GITHUB_ENV

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            ${{ env.ARCHIVE }}
