name: CD-Windows

on:
  release:
    types:
      - created # Trigger this workflow only when a new release is created

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  package-windows:
    name: Package Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Setup Fyne
        uses: ./.github/actions/fyne-windows-setup

      - name: Install Fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Read metadata
        shell: bash
        run: |
          APP_NAME=$(grep '^Name' FyneApp.toml | sed 's/.*= "\(.*\)"/\1/')
          APP_VERSION=$(grep '^Version' FyneApp.toml | sed 's/.*= "\(.*\)"/\1/')
          ARCH=$(go env GOARCH)

          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "ARCH=$ARCH" >> $GITHUB_ENV

          echo "Packaging $APP_NAME version $APP_VERSION for windows/$ARCH"

      - name: Package application
        env:
         COMMIT_HASH: ${{ github.sha }}
        run: fyne package --release --metadata Commit="$COMMIT_HASH"

      - name: Create ZIP archive
        shell: pwsh
        run: |
            $original = "$env:APP_NAME.exe"

            $zipName = "$env:APP_NAME-$env:APP_VERSION-windows-$env:ARCH.zip"

            Compress-Archive -Path $original -DestinationPath $zipName -Force

            "ARCHIVE=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            ${{ env.ARCHIVE }}